import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import backgroundImage from "../public/gray_shadow_bg.jpeg";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={"container"}>
          <Image
            className={"backgroundImage"}
            src={backgroundImage}
            alt="Page background"
            priority={true}
            fill
          />
          <div className={"content"}>
            <Link href={"/"} className="text-3xl font-bold ">
              Karta
            </Link>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
